### ISSUE TITLE
Bump Gradle version for tooling

### ISSUE THREAD

**Issue by a2geek** [AppleCommander/bastools#21]
Noting that current versions of Eclipse no longer reliably recognize older versions of Gradle projects reliably. Bump embedded version and adjust builds accordingly.

**Comment by ryandesign** [comment]
I see that in 71f28fc you updated to gradle 6.7.1 however when I build the project I see this message appear:

```
Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
```
